### PR TITLE
Fix http client doc

### PR DESCRIPTION
**Pull request by wwbmmm**
Solve #1492

### CODE REVIEW

**Comment by wwbmmm** [comment]
case 好像全挂了，下载thrift失败了

$ wget http://www.us.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz && tar -xf thrift-0.11.0.tar.gz && cd thrift-0.11.0/ && ./configure --prefix=/usr --with-rs=no --with-ruby=no --with-python=no --with-java=no --with-go=no --with-perl=no --with-php=no --with-csharp=no --with-erlang=no --with-lua=no --with-nodejs=no CXXFLAGS="-Wno-unused-variable" && make -j4 && sudo make install && cd -
--2021-07-23 11:13:55--  http://www.us.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz
Resolving www.us.apache.org (www.us.apache.org)... failed: Name or service not known.
wget: unable to resolve host address ‘www.us.apache.org’
The command "wget http://www.us.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz && tar -xf thrift-0.11.0.tar.gz && cd thrift-0.11.0/ && ./configure --prefix=/usr --with-rs=no --with-ruby=no --with-python=no --with-java=no --with-go=no --with-perl=no --with-php=no --with-csharp=no --with-erlang=no --with-lua=no --with-nodejs=no CXXFLAGS="-Wno-unused-variable" && make -j4 && sudo make install && cd -" failed and exited with 4 during .

**Comment by zyearn** [comment]
可以顺便也改一下docs/en/client.md吗？英文版的连接还指向一个中文的页面

**Comment by wwbmmm** [comment]
> 可以顺便也改一下docs/en/client.md吗？英文版的连接还指向一个中文的页面

加上了

**Comment by wwbmmm** [comment]
Thread 1 (Thread 0x7f9a65c0b9c0 (LWP 28564)):
#0  0x00007f9a65391783 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned long, int) () from /usr/lib/libtcmalloc_and_profiler.so.4
#1  0x00007f9a6539183b in tcmalloc::ThreadCache::ListTooLong(tcmalloc::ThreadCache::FreeList*, unsigned long) () from /usr/lib/libtcmalloc_and_profiler.so.4
#2  0x00007f9a653a3ee8 in tc_deletearray () from /usr/lib/libtcmalloc_and_profiler.so.4
#3  0x0000000000422900 in testing::internal::UnitTestImpl::~UnitTestImpl() ()
#4  0x00000000004220d3 in testing::UnitTest::~UnitTest() ()
#5  0x00007f9a6380bff8 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007f9a6380c045 in exit () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007f9a637f2837 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x0000000000406639 in _start ()
[runtest] 'bthread_unittest' failed, 18 succeeded


ut出错是bthread单测退出时出core，应该和当前的提交没有关系

**Pull request merged**
