### PR TITLE
add NOTICE.txt to address copyright

### PR DESCRIPTION
**Pull request by tanzhongyibidu**

### CODE REVIEW

**Comment by jamesge** [comment]
1. 确认下为什么两个文件的后缀名不统一
2. 这两个文件和已有的LICENSE是什么关系

**Comment by tanzhongyibidu** [comment]
Hi， gejun，
 
Let me explain it in more details：
 
1.     The LICENSE file located under the root of repo, should mention its license content and plus all third party license also.
For example , you can check https://github.com/apache/incubator-skywalking/blob/master/LICENSE
You can notice that it includes MIT /BSD license also for its included component.
 
2.     The NOTICE.txt located under the root of repo,  will be used to mention its copyright has belonged to apache.org
Here is one example by doris
https://github.com/apache/incubator-doris/blob/master/NOTICE.txt
 
3.     The Disclaimer file is used to describe its current status is under incubator.
Here is one example
https://github.com/apache/incubator-doris/blob/master/DISCLAIMER
and another one:
https://github.com/apache/incubator-skywalking/blob/master/DISCLAIMER
 
These files will be bunded into the release source tarball,
when user download and uncompress them,  user can easily find the license, copyright owner, and current status.

**Comment by jamesge** [comment]
Thanks for the explanation, however the first question remains: why there's an additional ".txt" extension to "NOTICE"

**Comment by tanzhongyibidu** [comment]
名字叫NOTICE，这是需要的，至于有的叫NOTICE.txt，有的叫NOTICE，都可以。
要不我改成NOTICE？

**Comment by jamesge** [comment]
ok，保持一致吧

**Comment by tanzhongyibidu** [comment]
BTW: I add another file named Disclaimer, when I update the diff, it is merged automatically.

**Pull request merged**
