### PR TITLE
Fix Brpc build tools error when only build static

### PR DESCRIPTION
**Pull request by stdpain**
protoc-gen-mcpack dependent on shared libraries. so when I build with `-DBUILD_SHARED_LIBS=OFF`. I'll got a link error

### CODE REVIEW

**Comment by jamesge** [comment]
@zyearn

**Comment by wwbmmm** [comment]
Can you make protoc-gen-mcpack  depends on static lib when `-DBUILD_SHARED_LIBS=OFF` ?

**Comment by stdpain** [comment]
> Can you make protoc-gen-mcpack depends on static lib when -DBUILD_SHARED_LIBS=OFF ?

fixed

**Comment by wwbmmm** [comment]
CI compile with cmake failed

**Comment by wwbmmm** [comment]
Similar PR: https://github.com/apache/incubator-brpc/pull/1667

**Comment by stdpain** [comment]
CI passed @wwbmmm @zyearn

**Comment by zyearn** [comment]
Thanks for the contribution!

**Pull request merged**
