### PR TITLE
fix typo in rdma doc

### PR DESCRIPTION
**Pull request by chenBright**
### What problem does this PR solve?

Issue Number:

Problem Summary:

### What is changed and the side effects?

Changed:

Side effects:
- Performance effects(性能影响):

- Breaking backward compatibility(向后兼容性): 

---
### Check List:
- Please make sure your changes are compilable(请确保你的更改可以通过编译).
- When providing us with a new feature, it is best to add related tests(如果你向我们增加一个新的功能, 请添加相关测试).
- Please follow [Contributor Covenant Code of Conduct](../CODE_OF_CONDUCT.md).(请遵循贡献者准则).

### CODE REVIEW

**Comment by zyearn** [comment]
这里”使能“应该是enable的意思

**Comment by chenBright** [comment]
> 这里”使能“应该是enable的意思

那这个表述是没问题的吗？

**Comment by Tuvie** [comment]
> 

这里原意确实就是使能(enable)

**Comment by chenBright** [comment]
> > 
> 
> 这里原意确实就是使能(enable)

哦哦，好的，那我close这个PR

**Pull request closed without merging**
