### PR TITLE
update getting_started doc to remove gperftools since it is not needed

### PR DESCRIPTION
**Pull request by tanzhongyi003**

### CODE REVIEW

**Comment by zyearn** [comment]
这个是为什么要删掉了？

**Comment by tanzhongyi003** [comment]
because  we have removed gperftool dependency from the source
so I think that we may need to update the doc also.

**Comment by zyearn** [comment]
But without gperftools, how can users do cpu/heap profiling? Do we remove this because of license issue?

**Comment by tanzhongyi003** [comment]
yes, you remove it because of license issue, 
do you still remember it?

**Comment by zyearn** [comment]
No I don't remember :) I can't find any context in the commit history too: https://github.com/apache/incubator-brpc/commits/master/LICENSE.

We still use those files, for example src/butil/gperftools_profiler.h, and their license is listed here https://github.com/apache/incubator-brpc/blob/master/LICENSE#L760, which is 3-clause BSD and it's apache compatible. 
There may be some misunderstandings here.

**Comment by tanzhongyi003** [comment]
ok, maybe you are right, I will close it now.

**Pull request closed without merging**
